### ISSUE TITLE
Feature checklist of YouPS button

### ISSUE THREAD

**Issue by soyapark** [haystack/YouPS#190]
See if both of us can implement following features and run on our email account to see any bug occured. 

- [ ] Hide this email until thursday, then remind me about it

- [ ] If this person sends email while professor X is out of town, reply and
tell them when professor X will be back

- [ ] If I don't get a reply to this email in 4 days, send a reminder
inquiry to the recipient

- [ ] If email arrives from one of these 3 people, forward it to professor Z

- [ ] Hide any email from these people until the weekend: use see_later()
